language: php

php:
    - 7.1
    - 7.0
    - 5.6
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer update --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/phpspec run --format dot -vvv --no-interaction
    - vendor/bin/phpunit
    - vendor/bin/phpstan analyse -c phpstan.neon -l max src/
